# Apply functions

# lapply() function is useful for performing operations on list objects and returns a list object of same length of original set. 

# runif can be used to produce random numbers; runif does not stand for run if. runif(n) generates n uniform random numbers between 0 and 1. runif(n, a, b) generates n uniform random numbers between a and b .

In [6]:
runif(5)

[1] 0.6311366 0.5961763 0.1130226 0.5735290 0.1365640

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     6   1     6   1     6  
[2,] 2     7   2     7   2     7  
[3,] 3     8   3     8   3     8  
[4,] 4     9   4     9   4     9  
[5,] 5    10   5    10   5    10

# Using apply in R

We start with the godfather of the family, apply, which operates on arrays (for simplicity we limit here to 2D arrays, aka, matrices). The R base manual tells us that it’s called as follows: apply(X, MARGIN, FUN, ...)
where:

    X is an array (a matrix if the dimension of the array is 2);
    MARGIN is a variable defining how the function is applied: when MARGIN=1, it applies over rows, whereas with MARGIN=2, it works over columns. Noticeably, with the construct MARGIN=c(1,2) it applies to both rows and columns;
    FUN is the function we want to apply and can be any R function, including a User Defined Function (more on functions in a separate post)

In [11]:
data <- matrix(c(1:10, 21:30), nrow = 5, ncol = 4)
data

[,1] [,2] [,3] [,4]
[1,] 1     6   21   26  
[2,] 2     7   22   27  
[3,] 3     8   23   28  
[4,] 4     9   24   29  
[5,] 5    10   25   30

In [12]:
apply(data, 1, mean)

[1] 13.5 14.5 15.5 16.5 17.5

In [13]:
apply(data, 2, mean)

[1]  3  8 23 28

In [15]:
m1 <- matrix(C<-(1:10),nrow=5, ncol=6)
m1

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     6   1     6   1     6  
[2,] 2     7   2     7   2     7  
[3,] 3     8   3     8   3     8  
[4,] 4     9   4     9   4     9  
[5,] 5    10   5    10   5    10

In [14]:
a_m1 <- apply(m1, 2, sum)
a_m1

[1] 15 40 15 40 15 40

In [16]:
a_m1 <- apply(m1, 1, sum)
a_m1

[1] 21 27 33 39 45

# lapply() function

# lapply() function is useful for performing operations on list objects and returns a list object of same length of original set. lapply() returns a list of the similar length as input list object, each element of which is the result of applying FUN to the corresponding element of list. lapply() takes list, vector or data frame as input and gives output in list. 

In [17]:
movies <- c("SPYDERMAN","BATMAN","VERTIGO","CHINATOWN")
movies_lower <-lapply(movies, tolower)
str(movies_lower)

List of 4
 $ : chr "spyderman"
 $ : chr "batman"
 $ : chr "vertigo"
 $ : chr "chinatown"


In [18]:
movies_lower

[[1]]
[1] "spyderman"

[[2]]
[1] "batman"

[[3]]
[1] "vertigo"

[[4]]
[1] "chinatown"

# we can use lapply to apply a function to each element in the list. 

In [19]:
data <- list(x = 1:5, y = 6:10, z = 11:15)
data

$x
[1] 1 2 3 4 5

$y
[1]  6  7  8  9 10

$z
[1] 11 12 13 14 15

In [20]:
lapply(data,  median)

$x
[1] 3

$y
[1] 8

$z
[1] 13

# sapply

sapply is the same as lapply, but returns a vector instead of a list.

In [21]:
sapply(data, FUN = median)

x  y  z 
 3  8 13

In [22]:
vec <- c(1:10)
vec

[1]  1  2  3  4  5  6  7  8  9 10

In [23]:
apply(vec, 1, sum)

ERROR: Error in apply(vec, 1, sum): dim(X) must have a positive length


# As you can see, this didn’t work because apply was expecting the data to have at least two dimensions. If your data is a vector you need to use lapply, sapply, or vapply instead

In [24]:
lapply(vec, sum)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] 6

[[7]]
[1] 7

[[8]]
[1] 8

[[9]]
[1] 9

[[10]]
[1] 10

# This function didn’t add up the values like we may have expected it to. This is because lapply applies treats the vector like a list, and applies the function to each point in the vector.

In [25]:
A<-c(1:9)
B<-c(1:12)
C<-c(1:15)
my.lst<-list(A,B,C)
lapply(my.lst, sum)

[[1]]
[1] 45

[[2]]
[1] 78

[[3]]
[1] 120