## Matrices in R

## Matrices are the R objects in which the elements are arranged in a two-dimensional rectangular layout. They contain elements of the same atomic types. Though we can create a matrix containing only characters or only logical values, they are not of much use. We use matrices containing numeric elements to be used in mathematical calculations.

## A Matrix is created using the matrix() function.

# The basic syntax for creating a matrix in R is −

# matrix(data, nrow, ncol, byrow, dimnames)

In [1]:
matrix(1:9, nrow = 3, ncol = 3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [2]:
matrix(1:9, nrow = 3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [3]:
matrix(1:9, nrow=3, byrow=TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

# It is possible to name the rows and columns of matrix during creation by passing a 2 element list to the argument dimnames

In [4]:
x <- matrix(1:9, nrow = 3, dimnames = list(c("X","Y","Z"), c("A","B","C")))

In [5]:
x

A B C
X 1 4 7
Y 2 5 8
Z 3 6 9

# These names can be accessed or changed with two helpful functions colnames() and rownames()

In [6]:
colnames(x)

[1] "A" "B" "C"

In [7]:
rownames(x)

[1] "X" "Y" "Z"

In [8]:
colnames(x) <- c("C1","C2","C3")

In [9]:
rownames(x) <- c("R1","R2","R3")

In [10]:
x

C1 C2 C3
R1 1  4  7 
R2 2  5  8 
R3 3  6  9

# Another way of creating a matrix is by using functions cbind() and rbind() as in column bind and row bind.

In [11]:
cbind(c(1,2,3),c(4,5,6))

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [12]:
rbind(c(1,2,3),c(4,5,6))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

#  Elements are arranged sequentially by row.

In [13]:
M <- matrix(c(3:14), nrow = 4, byrow = TRUE)

In [14]:
print(M)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


In [15]:
N <- matrix(c(3:14), nrow = 4)

In [16]:
print(N)

     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14


# # Define the column and row names.

In [17]:
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")

In [18]:
P <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(rownames, colnames))
print(P)

     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


# Accessing Elements of a Matrix

## Elements of a matrix can be accessed by using the column and row index of the element. We consider the matrix P above to find the specific elements below.

In [19]:
print(P[1,3])  # Access the element at 3rd column and 1st row.

[1] 5


In [20]:
print(P[4,2])  # Access the element at 2nd column and 4th row.

[1] 13


In [21]:
P

col1 col2 col3
row1  3    4    5  
row2  6    7    8  
row3  9   10   11  
row4 12   13   14

In [22]:
print(P[2,]) # Access only the  2nd row.

col1 col2 col3 
   6    7    8 


In [23]:
print(P[,3])  # Access only the 3rd column.

row1 row2 row3 row4 
   5    8   11   14 


# We can use negative integers to specify rows or columns to be excluded.

In [24]:
P[c(1,2),c(2,3)]    # select rows 1 & 2 and columns 2 & 3

col2 col3
row1 4    5   
row2 7    8

In [25]:
P[,]    # leaving row as well as column field blank will select entire matrix

col1 col2 col3
row1  3    4    5  
row2  6    7    8  
row3  9   10   11  
row4 12   13   14

In [26]:
P[-1,]    # select all rows except first

col1 col2 col3
row2  6    7    8  
row3  9   10   11  
row4 12   13   14

In [27]:
P[,-1]    # select all col except first

col2 col3
row1  4    5  
row2  7    8  
row3 10   11  
row4 13   14

# Using logical vector as index

## Two logical vectors can be used to index a matrix. In such situation, rows and columns where the value is TRUE is returned. These indexing vectors are recycled if necessary and can be mixed with integer vectors.

In [2]:
x <- matrix(1:9, nrow = 3, dimnames = list(c("X","Y","Z"), c("A","B","C")))

In [3]:
x

A B C
X 1 4 7
Y 2 5 8
Z 3 6 9

In [4]:
x[c(TRUE,FALSE,TRUE),c(TRUE,TRUE,FALSE)] #(first and third row, first and second column)

A B
X 1 4
Z 3 6

In [5]:
x[x>5]    # select elements greater than 5

[1] 6 7 8 9

# Using character vector as index

# Indexing with character vector is possible for matrix with named row or column. This can be mixed with integer or logical indexing.

In [6]:
x

A B C
X 1 4 7
Y 2 5 8
Z 3 6 9

In [7]:
x[,"A"]

X Y Z 
1 2 3

In [8]:
x[2:3,c("A","C")]

A C
Y 2 8
Z 3 9

# How to modify a matrix in R?

## We can combine assignment operator with the above learned methods for accessing elements of a matrix to modify it.

In [9]:
x[2,2] <- 10; x    # modify a single element

A B  C
X 1  4 7
Y 2 10 8
Z 3  6 9

In [10]:
x[x<5] <- 0; x    # modify elements less than 5

A B  C
X 0  0 7
Y 0 10 8
Z 0  6 9

# A common operation with matrix is to transpose it. This can be done with the function t()

In [11]:
t(x)    # transpose a matrix

X Y  Z
A 0  0 0
B 0 10 6
C 7  8 9

# We can add row or column using rbind() and cbind() function respectively. Similarly, it can be removed through reassignment.

In [12]:
cbind(x, c(1, 2, 3))    # add column

A B  C  
X 0  0 7 1
Y 0 10 8 2
Z 0  6 9 3

In [13]:
rbind(x,c(1,2,3))    # add row

A B  C
X 0  0 7
Y 0 10 8
Z 0  6 9
  1  2 3

In [15]:
x <- x[1:2,]; x    # remove last two row

A B  C
X 0  0 7
Y 0 10 8

In [16]:
# Dimension of matrix can be modified as well, using the dim() function.

In [17]:
x

A B  C
X 0  0 7
Y 0 10 8

In [18]:
dim(x) <- c(3,2); x    # change to 3X2 matrix

[,1] [,2]
[1,] 0    10  
[2,] 0     7  
[3,] 0     8

In [19]:
dim(x) <- c(1,6); x    # change to 1X6 matrix

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0    0    0    10   7    8

In [25]:
a<-matrix(1:8, nrow=3)

Warning message in matrix(1:8, nrow = 3):
"data length [8] is not a sub-multiple or multiple of the number of rows [3]"

In [26]:
a

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    1

# By default the matrix function reorders a vector into columns, but we can also tell R to use rows instead.

# Special matrices

# We can also create a matrix of a specified dimension where every element is the same.

In [29]:
z<- matrix(5, 3, 4) # 3*4 matrix of value 5
z

[,1] [,2] [,3] [,4]
[1,] 5    5    5    5   
[2,] 5    5    5    5   
[3,] 5    5    5    5

# We can create a matrix with specified elements on the diagonal. (And 0 on the off-diagonals.)

In [30]:
diag(3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [31]:
diag(1:4)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    2    0    0   
[3,] 0    0    3    0   
[4,] 0    0    0    4

In [32]:
x <- matrix(1:16, nrow = 4, dimnames = list(c("W","X","Y","Z"), c("A","B","C","D")))

In [33]:
x

A B C  D 
W 1 5  9 13
X 2 6 10 14
Y 3 7 11 15
Z 4 8 12 16

# Matrix Operations:

In [34]:
x = 1:9

In [35]:
y = 9:1

In [36]:
m1 = matrix(x, 3, 3)

In [37]:
m1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [38]:
m2 = matrix(y, 3, 3)

In [39]:
m2

[,1] [,2] [,3]
[1,] 9    6    3   
[2,] 8    5    2   
[3,] 7    4    1

In [40]:
print(m1+m2)

     [,1] [,2] [,3]
[1,]   10   10   10
[2,]   10   10   10
[3,]   10   10   10


In [41]:
print(m1-m2)

     [,1] [,2] [,3]
[1,]   -8   -2    4
[2,]   -6    0    6
[3,]   -4    2    8


In [42]:
print(m2-m1)

     [,1] [,2] [,3]
[1,]    8    2   -4
[2,]    6    0   -6
[3,]    4   -2   -8


In [43]:
print(m1*m2)

     [,1] [,2] [,3]
[1,]    9   24   21
[2,]   16   25   16
[3,]   21   24    9


In [44]:
print(m1/m2)

          [,1]      [,2]     [,3]
[1,] 0.1111111 0.6666667 2.333333
[2,] 0.2500000 1.0000000 4.000000
[3,] 0.4285714 1.5000000 9.000000


# Note that X * Y is not matrix multiplication. It is element by element multiplication. (Same for X / Y). Instead, matrix multiplication uses %*%.

# Other matrix functions include t() which gives the transpose of a matrix and solve() which returns the inverse of a square matrix if it is invertible.

In [45]:
m1 %*% m2 # matrix multiplication

[,1] [,2] [,3]
[1,]  90  54   18  
[2,] 114  69   24  
[3,] 138  84   30

In [46]:
z<-matrix(c(9, 2, -3, 2, 4, -2, -3, -2, 16), 3, byrow = TRUE)

In [47]:
z

[,1] [,2] [,3]
[1,]  9    2   -3  
[2,]  2    4   -2  
[3,] -3   -2   16

In [48]:
solve(z)

[,1]        [,2]        [,3]      
[1,]  0.12931034 -0.05603448 0.01724138
[2,] -0.05603448  0.29094828 0.02586207
[3,]  0.01724138  0.02586207 0.06896552

In [49]:
dim(z)

[1] 3 3

In [50]:
rowSums(z)

[1]  8  4 11

In [51]:
colSums(z)

[1]  8  4 11

In [52]:
rowMeans(z)

[1] 2.666667 1.333333 3.666667

In [53]:
colMeans(z)

[1] 2.666667 1.333333 3.666667

In [54]:
diag(z)

[1]  9  4 16

# Exercises

## 1) Create three vectors x,y,z with integers and each vector has 3 elements.Combine the three vectors to become a 3×3 matrix A where each column represents a vector. Change the row names to a,b,c.

# 2) Consider A=matrix(c(2,0,1,3), ncol=2) and B=matrix(c(5,2,4,-1), ncol=2).

a) Find A + B

b) Find A – B

# 3)Create a vector with 12 integers. Convert the vector to a 4*3 matrix  B  using  matrix(). Please change the column names to  x, y, z  and row names to  a, b, c, d. The argument  byrow  in  matrix()  is set to be  FALSE  by default. Please change it to  TRUE  and print  B  to see the differences.

# 4) Obtain the transpose matrix of  B  named  tB .

# 5) Extract a sub-matrix from  B  named  subB . It should be a 2×2 matrix which includes the last two rows of matrix  B  and their corresponding columns.

# 6) Using the the diag function build a diagonal matrix of size 4 with the following values in the diagonal 4,1,2,3.

# For exercises below use matrix A and B as given in Q.2

# 7) Find the solution for Ab,  b=c(7,4).

# 8) Find the solution for AB

# 9) Find the transpose matrix of A.

# 10) Find the inverse matrix of A.

# 11)
a) Create a list containing a vector, a matrix and a list.

b) Give names to the elements in the list.

c) Show the list.

d) Access the first element of the list.

e) Access the third element.

f) Access the list element using the name of the element.

g) Add element at the end of the list.

h) Remove the last element.

i)Print the 4th Element.

j) Update the 3rd Element.

k) Update the 3rd Element.

l) Create any two lists.

m) Merge the two lists.

n) Print the merged list.

o) Convert the lists to vectors.



# 12) If we have A1*M=A2  (Here * represents the conventional multiplication), A1 and A2 are random matrices, solve for  M.
(Hint- use the  runif()  and  solve()  functions. E.g.,  runif(9)  should give you 9 random numbers.    5x = 10, what's x?>solve(5,10) x is 2 here)

# 13)
a) create a 3* 4 matrix by arranging elements sequentially by row.

b) create a 3* 4 matrix by arranging elements sequentially by column.

c) Define the column and row names for the matrix created for a and b.
    
perform the following for matrix at a-

d) Access the element at 3rd column and 1st row.

e) Access the element at 2nd column and 4th row.

f) Access only the  2nd row.

g) Access only the 3rd column.

h) Create two 2x3 matrices.

i) Add the matrices.

j) Subtract the matrices

k) Multiply the matrices.

l) Divide the matrices


# 14)
bind the following vectors row wise and column wise to create matrix

a. a <- 1:5 ; b <- 1:5

b. a <- 1:5 ; b <- c('1', '2', '3', '4', '5')

c. a <- 1:5 ; b <- 1:4; c <- 1:3
